/*
Message {
  channel: <ref *1> TextChannel {
    type: 'text',
    deleted: false,
    id: '581255423164940290',
    name: 'general',
    rawPosition: 0,
    parentID: '581255423164940289',
    permissionOverwrites: Collection(0) [Map] {},
    topic: null,
    lastMessageID: '811736931124772864',
    rateLimitPerUser: 0,
    lastPinTimestamp: null,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '581255423164940288',
      shardID: 0,
      name: 'Matts Bot Testing',
      icon: null,
      splash: null,
      discoverySplash: null,
      region: 'us-west',
      memberCount: 2,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '581255423164940290',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1558652583596,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 100000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLCode: null,
      vanityURLUses: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      preferredLocale: 'en-US',
      ownerID: '546862575325806593',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [class LimitedCollection extends Collection],
      cache: [LimitedCollection [Map]],
      channel: [Circular *1]
    },
    nsfw: false,
    _typing: Map(0) {}
  },
  deleted: false,
  id: '811736931124772864',
  type: 'DEFAULT',
  system: false,
  content: 'something',
  author: User {
    id: '546862575325806593',
    system: false,
    locale: null,
    flags: UserFlags { bitfield: 0 },
    username: 'duckballer',
    bot: false,
    discriminator: '9060',
    avatar: '536564a5c57089df20dfde8ce49c3e4a',
    lastMessageID: '811736931124772864',
    lastMessageChannelID: '581255423164940290'
  },
  pinned: false,
  tts: false,
  nonce: '811737018475216896',
  embeds: [],
  attachments: Collection(0) [Map] {},
  createdTimestamp: 1613603565723,
  editedTimestamp: 0,
  reactions: ReactionManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    message: [Circular *2]
  },
  mentions: MessageMentions {
    everyone: false,
    users: Collection(0) [Map] {},
    roles: Collection(0) [Map] {},
    _members: null,
    _channels: null,
    crosspostedChannels: Collection(0) [Map] {}
  },
  webhookID: null,
  application: null,
  activity: null,
  _edits: [],
  flags: MessageFlags { bitfield: 0 },
  reference: null
}
*/